modLoader="javafml"
loaderVersion="[43,)"
license="Apache License V2.0"

[[mods]]
modId="colonymigration"
version="1.0"
displayName="Colony Migration Command"
description='''
Adds the command /colonymigrate to update MineColonies hut blocks to be used in a different colony
'''
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.colonymigration]]
modId="forge"
mandatory=true
versionRange="[43,)"
side="BOTH"
